core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("homeApp.urls")),
    path("", include("UsuarioApp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

UsuarioApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile, Position
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
        ]


class UserCreateForm(UserCreationForm, UserUpdateForm):
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()

    class Meta:
        model = User
        fields = UserUpdateForm.Meta.fields + ["password1", "password2"]

    def clean_password1(self):
        password1 = self.cleaned_data.get("password1")
        validate_password(password1)
        return password1

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords do not match")

        return cleaned_data


class ProfileUpdateForm(forms.ModelForm):
    image = forms.ImageField(
        label="Imagen",
        widget=forms.FileInput(attrs={"class": "hidden", "id": "id_image"}),
        required=False,
    )

    class Meta:
        model = Profile
        fields = ["image"]

    def clean_image(self):
        image = self.cleaned_data.get("image")
        if image and image.size > 5 * 1024 * 1024:
            raise forms.ValidationError(
                "El tamaño del archivo de imagen no debe exceder los 5 MB."
            )
        return image


class ProfileCreateForm(ProfileUpdateForm):
    position_FK = forms.ModelChoiceField(
        label="Cargo",
        queryset=Position.objects.exclude(pk=1),
        widget=forms.Select(
            attrs={
                "class": "bg-white focus:outline-none border border-gray-300 rounded-lg py-2 px-4 block w-full appearance-none leading-normal text-gray-700 mb-3"
            }
        ),
    )

    class Meta(ProfileUpdateForm.Meta):
        fields = ProfileUpdateForm.Meta.fields + ["position_FK"]

templates/pages/usuarios/registro_usuario.html
{% extends "components/Layout/base_pages.html" %}
{% load static %} 
{% load tailwind_filters %}

{% block head_title %}
  Registrar Usuario
{% endblock head_title %}

{% block content_pages %}

  <h1 class="max-w-2xl font-bold tracking-tight text-gray-900 text-2xl mb-4">Registrar Usuario</h1>
  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}

      {% include 'components/input_perfil.html' with img="/static/img/profile.webp" %}
      
      <label for="id_position_FK" class="block text-gray-700 text-sm font-bold mb-2">
        Cargo
      </label>
      {{ profile_form.position_FK }}
      {{ user_form|crispy }}

      {% include "components/btn/button.html" with button_text="Guardar cambios" %}
      
  </form>

  {% include 'components/mensajes.html' %}  

{% endblock content_pages %}    

{% block javascript %}

  <script defer src="{% static "js/script.js" %}"></script>

{% endblock javascript %}

templates/pages/usuarios/usuarios_lista.html
{% extends 'components/Layout/base_extendido.html' %}
{% load static %}   

{% block content_main %} 

{% if users %}
    <ul class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">

      {% for user, verifition in verification_users %}
      
        <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
          <div class="flex w-full items-center justify-between space-x-6 p-6">
            <div class="flex-1 truncate">
              <div class="flex items-center space-x-3">
                <h3 class="truncate text-sm font-medium text-gray-900">
                  {{ user.username}}   
                </h3>
                
                <span class="inline-flex flex-shrink-0 items-center rounded-full bg-green-50 px-1.5 py-0.5 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                  {{ user.profile.position_FK }}
                </span>
              </div>
              <p class="mt-1 truncate text-sm text-gray-500 flex justify-between">
                {{ user.first_name }} {{ user.last_name }}
                {% if verifition %}
                    <span class="inline-flex flex-shrink-0 items-center rounded-full bg-green-50 px-1.5 py-0.5 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                      Verificado
                    </span>
                {% else %}
                    <span class="inline-flex flex-shrink-0 items-center rounded-full bg-red-50 px-1.5 py-0.5 text-xs font-medium text-red-700 ring-1 ring-inset ring-green-600/20">
                      No Verificado
                    </span> 
                {% endif %}
              </p>
            </div>
            <img class="h-10 w-10 flex-shrink-0 rounded-full bg-gray-300" src="{{ user.profile.image.url }}" alt="perfil">
          </div>
          <div>
            <div class="-mt-px flex divide-x divide-gray-200">
              <div class="flex w-0 flex-1">
                <a href="mailto:{{ user.email }}" class="relative -mr-px inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900">
                  <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path d="M3 4a2 2 0 00-2 2v1.161l8.441 4.221a1.25 1.25 0 001.118 0L19 7.162V6a2 2 0 00-2-2H3z" />
                    <path d="M19 8.839l-7.77 3.885a2.75 2.75 0 01-2.46 0L1 8.839V14a2 2 0 002 2h14a2 2 0 002-2V8.839z" />
                  </svg>
                  Email
                </a>
              </div>
            </div>
          </div>
        </li>
        
      {% endfor %}

    </ul>  

    {% include 'components/paginador.html' %}  
  {% else %}

    <strong>NO HAY REGISTROS</strong>
      
  {% endif %}

{% endblock content_main %}